

const SUPABASE_URL = "https://wijgkrsoummkhwjxnjtx.supabase.co"
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpamdrcnNvdW1ta2h3anhuanR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzI2OTI0NDQsImV4cCI6MTk4ODI2ODQ0NH0.WDfqSPquJKg1qhdyCztrziv_ZvHoy1xOvZeXqSy1kUg"

module.exports = {SUPABASE_KEY , SUPABASE_URL}